package com.hades.farm.core.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TAccountIntegralFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.amount_before
     *
     * @mbggenerated
     */
    private BigDecimal amountBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.amount_after
     *
     * @mbggenerated
     */
    private BigDecimal amountAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_integral_flow.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral_flow
     *
     * @mbggenerated
     */
    public TAccountIntegralFlow(){}
    public TAccountIntegralFlow(Long id, Long userId, String type, BigDecimal amount, BigDecimal amountBefore, BigDecimal amountAfter, String remarks, Date addTime) {
        this.id = id;
        this.userId = userId;
        this.type = type;
        this.amount = amount;
        this.amountBefore = amountBefore;
        this.amountAfter = amountAfter;
        this.remarks = remarks;
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.id
     *
     * @return the value of t_account_integral_flow.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.user_id
     *
     * @return the value of t_account_integral_flow.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.type
     *
     * @return the value of t_account_integral_flow.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.amount
     *
     * @return the value of t_account_integral_flow.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.amount_before
     *
     * @return the value of t_account_integral_flow.amount_before
     *
     * @mbggenerated
     */
    public BigDecimal getAmountBefore() {
        return amountBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.amount_after
     *
     * @return the value of t_account_integral_flow.amount_after
     *
     * @mbggenerated
     */
    public BigDecimal getAmountAfter() {
        return amountAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.remarks
     *
     * @return the value of t_account_integral_flow.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_integral_flow.add_time
     *
     * @return the value of t_account_integral_flow.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public void setAmountBefore(BigDecimal amountBefore) {
        this.amountBefore = amountBefore;
    }

    public void setAmountAfter(BigDecimal amountAfter) {
        this.amountAfter = amountAfter;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}