package com.hades.farm.core.data.entity;

import java.util.Date;

public class TDuckBreeding {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.num_harvest
     *
     * @mbggenerated
     */
    private Integer numHarvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.day
     *
     * @mbggenerated
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.acc_no_feed
     *
     * @mbggenerated
     */
    private Integer accNoFeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.if_feed
     *
     * @mbggenerated
     */
    private Integer isFeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_duck_breeding.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    public TDuckBreeding(){}
    public TDuckBreeding(Long id, Long userId, Integer num, Integer numHarvest, Integer day, Integer accNoFeed, Integer status, Integer isFeed, Date addTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.num = num;
        this.numHarvest = numHarvest;
        this.day = day;
        this.accNoFeed = accNoFeed;
        this.status = status;
        this.isFeed = isFeed;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.id
     *
     * @return the value of t_duck_breeding.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.user_id
     *
     * @return the value of t_duck_breeding.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.num
     *
     * @return the value of t_duck_breeding.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.num_harvest
     *
     * @return the value of t_duck_breeding.num_harvest
     *
     * @mbggenerated
     */
    public Integer getNumHarvest() {
        return numHarvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.day
     *
     * @return the value of t_duck_breeding.day
     *
     * @mbggenerated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.acc_no_feed
     *
     * @return the value of t_duck_breeding.acc_no_feed
     *
     * @mbggenerated
     */
    public Integer getAccNoFeed() {
        return accNoFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.status
     *
     * @return the value of t_duck_breeding.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.if_feed
     *
     * @return the value of t_duck_breeding.if_feed
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.add_time
     *
     * @return the value of t_duck_breeding.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_duck_breeding.update_time
     *
     * @return the value of t_duck_breeding.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public void setNumHarvest(Integer numHarvest) {
        this.numHarvest = numHarvest;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public void setAccNoFeed(Integer accNoFeed) {
        this.accNoFeed = accNoFeed;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }



    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getIsFeed() {
        return isFeed;
    }

    public void setIsFeed(Integer isFeed) {
        this.isFeed = isFeed;
    }
}