package com.hades.farm.core.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TEggWarehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.egg
     *
     * @mbggenerated
     */
    private Integer egg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.egg_doing
     *
     * @mbggenerated
     */
    private Integer eggDoing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.duck
     *
     * @mbggenerated
     */
    private Integer duck;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.if_hot
     *
     * @mbggenerated
     */
    private Integer ifHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.if_harvest
     *
     * @mbggenerated
     */
    private Integer ifHarvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.if_steal
     *
     * @mbggenerated
     */
    private Integer ifSteal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.all_sell
     *
     * @mbggenerated
     */
    private Integer allSell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.all_profit
     *
     * @mbggenerated
     */
    private BigDecimal allProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.all_integral
     *
     * @mbggenerated
     */
    private BigDecimal allIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_egg_warehouse.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    public TEggWarehouse(){}
    public TEggWarehouse(Long id, Long userId, Integer egg, Integer eggDoing, Integer duck, Integer ifHot, Integer ifHarvest, Integer ifSteal, Integer allSell, BigDecimal allProfit, BigDecimal allIntegral, Date addTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.egg = egg;
        this.eggDoing = eggDoing;
        this.duck = duck;
        this.ifHot = ifHot;
        this.ifHarvest = ifHarvest;
        this.ifSteal = ifSteal;
        this.allSell = allSell;
        this.allProfit = allProfit;
        this.allIntegral = allIntegral;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.id
     *
     * @return the value of t_egg_warehouse.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.user_id
     *
     * @return the value of t_egg_warehouse.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.egg
     *
     * @return the value of t_egg_warehouse.egg
     *
     * @mbggenerated
     */
    public Integer getEgg() {
        return egg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.egg_doing
     *
     * @return the value of t_egg_warehouse.egg_doing
     *
     * @mbggenerated
     */
    public Integer getEggDoing() {
        return eggDoing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.duck
     *
     * @return the value of t_egg_warehouse.duck
     *
     * @mbggenerated
     */
    public Integer getDuck() {
        return duck;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.if_hot
     *
     * @return the value of t_egg_warehouse.if_hot
     *
     * @mbggenerated
     */
    public Integer getIfHot() {
        return ifHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.if_harvest
     *
     * @return the value of t_egg_warehouse.if_harvest
     *
     * @mbggenerated
     */
    public Integer getIfHarvest() {
        return ifHarvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.if_steal
     *
     * @return the value of t_egg_warehouse.if_steal
     *
     * @mbggenerated
     */
    public Integer getIfSteal() {
        return ifSteal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.all_sell
     *
     * @return the value of t_egg_warehouse.all_sell
     *
     * @mbggenerated
     */
    public Integer getAllSell() {
        return allSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.all_profit
     *
     * @return the value of t_egg_warehouse.all_profit
     *
     * @mbggenerated
     */
    public BigDecimal getAllProfit() {
        return allProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.all_integral
     *
     * @return the value of t_egg_warehouse.all_integral
     *
     * @mbggenerated
     */
    public BigDecimal getAllIntegral() {
        return allIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.add_time
     *
     * @return the value of t_egg_warehouse.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_egg_warehouse.update_time
     *
     * @return the value of t_egg_warehouse.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setEgg(Integer egg) {
        this.egg = egg;
    }

    public void setEggDoing(Integer eggDoing) {
        this.eggDoing = eggDoing;
    }

    public void setDuck(Integer duck) {
        this.duck = duck;
    }


    public void setIfHot(Integer ifHot) {
        this.ifHot = ifHot;
    }

    public void setIfHarvest(Integer ifHarvest) {
        this.ifHarvest = ifHarvest;
    }

    public void setIfSteal(Integer ifSteal) {
        this.ifSteal = ifSteal;
    }

    public void setAllSell(Integer allSell) {
        this.allSell = allSell;
    }

    public void setAllProfit(BigDecimal allProfit) {
        this.allProfit = allProfit;
    }

    public void setAllIntegral(BigDecimal allIntegral) {
        this.allIntegral = allIntegral;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}