package com.hades.farm.core.data.entity;

import java.util.Date;

public class TIdentityCardRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_identity_card_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_identity_card_record.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_identity_card_record.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_identity_card_record.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_identity_card_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    public TIdentityCardRecord() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_card_record
     *
     * @mbggenerated
     */
    public TIdentityCardRecord(Long id, Long userId, String realName, String idNo, Date createTime) {
        this.id = id;
        this.userId = userId;
        this.realName = realName;
        this.idNo = idNo;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_identity_card_record.id
     *
     * @return the value of t_identity_card_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_identity_card_record.user_id
     *
     * @return the value of t_identity_card_record.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_identity_card_record.real_name
     *
     * @return the value of t_identity_card_record.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_identity_card_record.id_no
     *
     * @return the value of t_identity_card_record.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_identity_card_record.create_time
     *
     * @return the value of t_identity_card_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}