package com.hades.farm.core.data.entity;

import java.util.Date;

public class TOrders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.if_cashback
     *
     * @mbggenerated
     */
    private Integer ifCashback;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    public TOrders(){}
    public TOrders(Long id, Long userId, Integer type, Integer num, Integer status, Date addTime, Date updateTime, Integer ifCashback) {
        this.id = id;
        this.userId = userId;
        this.type = type;
        this.num = num;
        this.status = status;
        this.addTime = addTime;
        this.updateTime = updateTime;
        this.ifCashback = ifCashback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.id
     *
     * @return the value of t_orders.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.user_id
     *
     * @return the value of t_orders.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.type
     *
     * @return the value of t_orders.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.num
     *
     * @return the value of t_orders.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.status
     *
     * @return the value of t_orders.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.add_time
     *
     * @return the value of t_orders.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.update_time
     *
     * @return the value of t_orders.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.if_cashback
     *
     * @return the value of t_orders.if_cashback
     *
     * @mbggenerated
     */
    public Integer getIfCashback() {
        return ifCashback;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void setIfCashback(Integer ifCashback) {
        this.ifCashback = ifCashback;
    }
}