package com.hades.farm.core.data.entity;

public class TPlatformWarehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse.egg_num
     *
     * @mbggenerated
     */
    private Integer eggNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse.duck_num
     *
     * @mbggenerated
     */
    private Integer duckNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse.dog_num
     *
     * @mbggenerated
     */
    private Integer dogNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    public TPlatformWarehouse(Long id, Integer eggNum, Integer duckNum, Integer dogNum) {
        this.id = id;
        this.eggNum = eggNum;
        this.duckNum = duckNum;
        this.dogNum = dogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse.id
     *
     * @return the value of t_platform_warehouse.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse.egg_num
     *
     * @return the value of t_platform_warehouse.egg_num
     *
     * @mbggenerated
     */
    public Integer getEggNum() {
        return eggNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse.duck_num
     *
     * @return the value of t_platform_warehouse.duck_num
     *
     * @mbggenerated
     */
    public Integer getDuckNum() {
        return duckNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse.dog_num
     *
     * @return the value of t_platform_warehouse.dog_num
     *
     * @mbggenerated
     */
    public Integer getDogNum() {
        return dogNum;
    }
}