package com.hades.farm.core.data.entity;

import java.util.Date;

public class TPlatformWarehouseFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.p_id
     *
     * @mbggenerated
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.goods
     *
     * @mbggenerated
     */
    private String goods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.num_before
     *
     * @mbggenerated
     */
    private Integer numBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.num_after
     *
     * @mbggenerated
     */
    private Integer numAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_warehouse_flow.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    public TPlatformWarehouseFlow(){}
    public TPlatformWarehouseFlow(Long id, Long pId, String goods, String type, Integer num, Integer numBefore, Integer numAfter, String remarks, Date addTime) {
        this.id = id;
        this.pId = pId;
        this.goods = goods;
        this.type = type;
        this.num = num;
        this.numBefore = numBefore;
        this.numAfter = numAfter;
        this.remarks = remarks;
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.id
     *
     * @return the value of t_platform_warehouse_flow.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.p_id
     *
     * @return the value of t_platform_warehouse_flow.p_id
     *
     * @mbggenerated
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.goods
     *
     * @return the value of t_platform_warehouse_flow.goods
     *
     * @mbggenerated
     */
    public String getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.type
     *
     * @return the value of t_platform_warehouse_flow.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.num
     *
     * @return the value of t_platform_warehouse_flow.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.num_before
     *
     * @return the value of t_platform_warehouse_flow.num_before
     *
     * @mbggenerated
     */
    public Integer getNumBefore() {
        return numBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.num_after
     *
     * @return the value of t_platform_warehouse_flow.num_after
     *
     * @mbggenerated
     */
    public Integer getNumAfter() {
        return numAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.remarks
     *
     * @return the value of t_platform_warehouse_flow.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_warehouse_flow.add_time
     *
     * @return the value of t_platform_warehouse_flow.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setpId(Long pId) {
        this.pId = pId;
    }

    public void setGoods(String goods) {
        this.goods = goods;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public void setNumBefore(Integer numBefore) {
        this.numBefore = numBefore;
    }

    public void setNumAfter(Integer numAfter) {
        this.numAfter = numAfter;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}