package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TAccountIntegral;

public interface TAccountIntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int insert(TAccountIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int insertSelective(TAccountIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    TAccountIntegral selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAccountIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAccountIntegral record);
}