package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TAccountTicketFlow;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TAccountTicketFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_ticket_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_ticket_flow
     *
     * @mbggenerated
     */
    int insert(TAccountTicketFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_ticket_flow
     *
     * @mbggenerated
     */
    int insertSelective(TAccountTicketFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_ticket_flow
     *
     * @mbggenerated
     */
    TAccountTicketFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_ticket_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAccountTicketFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_ticket_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAccountTicketFlow record);

    /**
     * 获取佣金记录
     *
     * @param userId
     * @param offset
     * @param size
     * @return
     */
    List<TAccountTicketFlow> findTicketRecord(@Param("userId") long userId, @Param("offset") int offset, @Param("size") int size);

    /**
     * 获取交易记录
     *
     * @param userId
     * @param offset
     * @param size
     * @return
     */
    List<TAccountTicketFlow> findAccountRecord(@Param("userId") long userId, @Param("offset") int offset, @Param("size") int size);

}