package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TAccountIntegral;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;

public interface TAccountIntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int insert(TAccountIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int insertSelective(TAccountIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    TAccountIntegral selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAccountIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAccountIntegral record);

    TAccountIntegral queryByUserId(long userId);

    int updateIntegralByUserId(TAccountIntegral accountIntegral);

    void updateAccountIntegralForAccGain(@Param("acc_gain") BigDecimal acc_gain, @Param("user_id") long user_id);
}