package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TBackReward;

public interface TBackRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_back_reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_back_reward
     *
     * @mbggenerated
     */
    int insert(TBackReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_back_reward
     *
     * @mbggenerated
     */
    int insertSelective(TBackReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_back_reward
     *
     * @mbggenerated
     */
    TBackReward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_back_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBackReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_back_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBackReward record);
}