package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TDuckBreeding;

public interface TDuckBreedingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    int insert(TDuckBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    int insertSelective(TDuckBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    TDuckBreeding selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TDuckBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_breeding
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TDuckBreeding record);
}