package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.dto.requestDto.BreedingRequestDto;
import com.hades.farm.core.data.dto.requestDto.BuyGoodsRequestDto;
import com.hades.farm.core.data.entity.TDuckWarehouse;

public interface TDuckWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_warehouse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_warehouse
     *
     * @mbggenerated
     */
    int insert(TDuckWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_warehouse
     *
     * @mbggenerated
     */
    int insertSelective(TDuckWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_warehouse
     *
     * @mbggenerated
     */
    TDuckWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TDuckWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duck_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TDuckWarehouse record);

    TDuckWarehouse selectByUserId(long userId);

    int updateDuckWareHouseBreedingDuck(BreedingRequestDto requestDto);

    int updateDuckWareHouseBuyDuck(BuyGoodsRequestDto requestDto);
}