package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.dto.resultDto.HarvestResultDto;
import com.hades.farm.core.data.entity.TEggBreeding;

import java.util.List;
import java.util.Map;

public interface TEggBreedingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int insert(TEggBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int insertSelective(TEggBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    TEggBreeding selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TEggBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TEggBreeding record);

    Map queryHaveBreed(Map map);

    List<TEggBreeding> queryBreedingList(long userId);

    List<Map> queryBreeList(long userId, int offSet, int pageSize);

    int queryCanStealNum(long userId);

    int updateOfStealByOther(long userId);

    List<HarvestResultDto> queryCanHarvestList(long userId);

    int harvestOfDoing(long userId);

    int harvestOfDone(long userId);

    int queryHarvestFreeze(long userId);

    int queryHarvestNum(long userId);
}