package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TEggBreeding;

import java.util.Map;

public interface TEggBreedingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int insert(TEggBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int insertSelective(TEggBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    TEggBreeding selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TEggBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_breeding
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TEggBreeding record);

    Map queryHaveBreed(Map map);
}