package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.dto.requestDto.BreedingRequestDto;
import com.hades.farm.core.data.dto.requestDto.BuyGoodsRequestDto;
import com.hades.farm.core.data.entity.TEggWarehouse;

public interface TEggWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    int insert(TEggWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    int insertSelective(TEggWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    TEggWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TEggWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_egg_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TEggWarehouse record);

    TEggWarehouse selectByUserId(Long userId);

    int updateEggWareHouseBreedingEgg(BreedingRequestDto requestDto);

    int updateEggWareHouseBuyDuck(BuyGoodsRequestDto requestDto);
}