package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TNotice;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated
     */
    int insert(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated
     */
    int insertSelective(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated
     */
    TNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TNotice record);

    /**
     * 获取用户所有通知
     *
     * @param userId
     * @return
     */
    List<TNotice> getNoticeByUserId(long userId);

    List<TNotice> getNoticeByUserIdOfnum(@Param("userId") long userId, @Param("num") int num);

}