package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.dto.requestDto.BuyGoodsRequestDto;
import com.hades.farm.core.data.dto.requestDto.OrderQueryRequestDto;
import com.hades.farm.core.data.dto.resultDto.OrderUserResultDto;
import com.hades.farm.core.data.entity.TOrders;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    int insert(TOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    int insertSelective(TOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    TOrders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrders record);

    int updateOrderOfBuy(BuyGoodsRequestDto requestDto);

    List<TOrders> getUnCachBack();

    int updateCashBack(long orderId);

    List<OrderUserResultDto> queryOrderListByCondition(OrderQueryRequestDto requestDto);
}