package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TPayItem;

public interface TPayItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_item
     *
     * @mbggenerated
     */
    int insert(TPayItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_item
     *
     * @mbggenerated
     */
    int insertSelective(TPayItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_item
     *
     * @mbggenerated
     */
    TPayItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPayItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPayItem record);
}