package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.dto.requestDto.UpdatePlatFormWarehouseRequestDto;
import com.hades.farm.core.data.entity.TPlatformWarehouse;

public interface TPlatformWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    int insert(TPlatformWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    int insertSelective(TPlatformWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    TPlatformWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPlatformWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPlatformWarehouse record);

    TPlatformWarehouse queryPlatformWarehouse();

    int updatePlatFormWarehouse(UpdatePlatFormWarehouseRequestDto requestDto);
}