package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TPlatformWarehouseFlow;

public interface TPlatformWarehouseFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    int insert(TPlatformWarehouseFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    int insertSelective(TPlatformWarehouseFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    TPlatformWarehouseFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPlatformWarehouseFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_warehouse_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPlatformWarehouseFlow record);
}