package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TRelation;

public interface TRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    int insert(TRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    int insertSelective(TRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    TRelation selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRelation record);
}