package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TWithdraw;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int insert(TWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int insertSelective(TWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    TWithdraw selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TWithdraw record);

    /**
     * 获取提现记录
     *
     * @param userId
     * @param offset
     * @param size
     * @return
     */
    List<TWithdraw> findWithdraw(@Param("userId") long userId, @Param("offset") int offset, @Param("size") int size);
}