package com.hades.farm.core.data.mapper;

import com.hades.farm.core.data.entity.TWithdraw;

public interface TWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int insert(TWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int insertSelective(TWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    TWithdraw selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TWithdraw record);
}